on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          compose-file: "./docker/docker-compose.yml"
          services: |
            "helloworld2"
            "helloworld3"
      - uses: ./
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
