name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      #checkov:skip=CKV_GHA_7: required
      TAG_NAME:
        description: "Tag name that the major tag will point to"
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

permissions: {}

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: releaseNewActionVersion
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@23f4c6f12633a2da8f44938b71fde9afec138fb4 # v0.4.0
        with:
          source-tag: ${{ env.TAG_NAME }}
